[tool.poetry]
name = "embedded-inference"
version = "0.1.0"
description = ""
authors = ["charitarthchugh <37895518+charitarthchugh@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "embedded_inference"}]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.95.0"
onnxruntime-gpu = "^1.14.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
